Tsystem/Controllers/CourseSchedulesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Tsystem.Models;

namespace Tsystem.Controllers
{
    public class CourseSchedulesController : Controller
    {
        private Database1Entities db = new Database1Entities();

        // GET: CourseSchedules
        public ActionResult Index()
        {
            var courseSchedules = db.CourseSchedules.Include(c => c.CertificateTemplate).Include(c => c.CourseClassification);
            return View(courseSchedules.ToList());
        }

        // GET: CourseSchedules/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CourseSchedule courseSchedule = db.CourseSchedules.Find(id);
            if (courseSchedule == null)
            {
                return HttpNotFound();
            }
            return View(courseSchedule);
        }

        // GET: CourseSchedules/Create
        public ActionResult Create()
        {
            ViewBag.Certificate_ID = new SelectList(db.CertificateTemplates, "Certificate_ID", "Certificate_Template");
            ViewBag.Classification_ID = new SelectList(db.CourseClassifications, "Classification_ID", "Classification_Name");
            return View();
        }

        // POST: CourseSchedules/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Course_ID,Course_Title,Description,Language,Date,Start_Time,End_Time,Course_Status,Seats_Number,Course_Place,user_Type,Classification_ID,Course_Type,Certificate_ID,Trainer_Name")] CourseSchedule courseSchedule)
        {
            if (ModelState.IsValid)
            {
                db.CourseSchedules.Add(courseSchedule);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.Certificate_ID = new SelectList(db.CertificateTemplates, "Certificate_ID", "Certificate_Template", courseSchedule.Certificate_ID);
            ViewBag.Classification_ID = new SelectList(db.CourseClassifications, "Classification_ID", "Classification_Name", courseSchedule.Classification_ID);
            return View(courseSchedule);
        }

        // GET: CourseSchedules/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CourseSchedule courseSchedule = db.CourseSchedules.Find(id);
            if (courseSchedule == null)
            {
                return HttpNotFound();
            }
            ViewBag.Certificate_ID = new SelectList(db.CertificateTemplates, "Certificate_ID", "Certificate_Template", courseSchedule.Certificate_ID);
            ViewBag.Classification_ID = new SelectList(db.CourseClassifications, "Classification_ID", "Classification_Name", courseSchedule.Classification_ID);
            return View(courseSchedule);
        }

        // POST: CourseSchedules/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Course_ID,Course_Title,Description,Language,Date,Start_Time,End_Time,Course_Status,Seats_Number,Course_Place,user_Type,Classification_ID,Course_Type,Certificate_ID,Trainer_Name")] CourseSchedule courseSchedule)
        {
            if (ModelState.IsValid)
            {
                db.Entry(courseSchedule).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.Certificate_ID = new SelectList(db.CertificateTemplates, "Certificate_ID", "Certificate_Template", courseSchedule.Certificate_ID);
            ViewBag.Classification_ID = new SelectList(db.CourseClassifications, "Classification_ID", "Classification_Name", courseSchedule.Classification_ID);
            return View(courseSchedule);
        }

        // GET: CourseSchedules/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CourseSchedule courseSchedule = db.CourseSchedules.Find(id);
            if (courseSchedule == null)
            {
                return HttpNotFound();
            }
            return View(courseSchedule);
        }

        // POST: CourseSchedules/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            CourseSchedule courseSchedule = db.CourseSchedules.Find(id);
            db.CourseSchedules.Remove(courseSchedule);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Tsystem/Controllers/Registered_in_the_courseController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Tsystem.Models;

namespace Tsystem.Controllers
{
    public class Registered_in_the_courseController : Controller
    {
        private Database1Entities db = new Database1Entities();

        // GET: Registered_in_the_course
        public ActionResult Index(string searchName, string searchCourse)
        {
            var registered_in_the_courses = db.Registered_in_the_courses.Include(r => r.CourseSchedule).Include(r => r.User);

            if (!String.IsNullOrEmpty(searchName))
            {
                registered_in_the_courses = registered_in_the_courses.Where(s => s.User.Ar_Name.Contains(searchName));
            }

            if (!String.IsNullOrEmpty(searchCourse))
            {
                registered_in_the_courses = registered_in_the_courses.Where(x => x.CourseSchedule.Course_Title.Contains(searchCourse));
            }

            ViewBag.SearchName = searchName;
            ViewBag.SearchCourse = searchCourse;

            return View(registered_in_the_courses.ToList());
        }

        // GET: Registered_in_the_course/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Registered_in_the_course registered_in_the_course = db.Registered_in_the_courses.Find(id);
            if (registered_in_the_course == null)
            {
                return HttpNotFound();
            }
            return View(registered_in_the_course);
        }

        // GET: Registered_in_the_course/Create
        public ActionResult Create()
        {
            ViewBag.Course_ID = new SelectList(db.CourseSchedules, "Course_ID", "Course_Title");
            ViewBag.User_ID = new SelectList(db.Users, "User_ID", "Ar_Name");
            return View();
        }

        // POST: Registered_in_the_course/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "User_ID,Course_ID,Attendance_Status,Evaluation_Status,Certificate_Status")] Registered_in_the_course registered_in_the_course)
        {
            if (ModelState.IsValid)
            {
                db.Registered_in_the_courses.Add(registered_in_the_course);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.Course_ID = new SelectList(db.CourseSchedules, "Course_ID", "Course_Title", registered_in_the_course.Course_ID);
            ViewBag.User_ID = new SelectList(db.Users, "User_ID", "Ar_Name", registered_in_the_course.User_ID);
            return View(registered_in_the_course);
        }

        // GET: Registered_in_the_course/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Registered_in_the_course registered_in_the_course = db.Registered_in_the_courses.Find(id);
            if (registered_in_the_course == null)
            {
                return HttpNotFound();
            }
            ViewBag.Course_ID = new SelectList(db.CourseSchedules, "Course_ID", "Course_Title", registered_in_the_course.Course_ID);
            ViewBag.User_ID = new SelectList(db.Users, "User_ID", "Ar_Name", registered_in_the_course.User_ID);
            return View(registered_in_the_course);
        }

        // POST: Registered_in_the_course/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "User_ID,Course_ID,Attendance_Status,Evaluation_Status,Certificate_Status")] Registered_in_the_course registered_in_the_course)
        {
            if (ModelState.IsValid)
            {
                db.Entry(registered_in_the_course).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.Course_ID = new SelectList(db.CourseSchedules, "Course_ID", "Course_Title", registered_in_the_course.Course_ID);
            ViewBag.User_ID = new SelectList(db.Users, "User_ID", "Ar_Name", registered_in_the_course.User_ID);
            return View(registered_in_the_course);
        }

        // GET: Registered_in_the_course/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Registered_in_the_course registered_in_the_course = db.Registered_in_the_courses.Find(id);
            if (registered_in_the_course == null)
            {
                return HttpNotFound();
            }
            return View(registered_in_the_course);
        }

        // POST: Registered_in_the_course/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Registered_in_the_course registered_in_the_course = db.Registered_in_the_courses.Find(id);
            db.Registered_in_the_courses.Remove(registered_in_the_course);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Tsystem/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Training System</title>
    @*@Styles.Render("~/Content/css")*@ @*comment*@
    @*@Scripts.Render("~/bundles/modernizr")*@
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
    <style>
        @@import url('https://fonts.googleapis.com/css2?family=Noto+Kufi+Arabic:wght@100..900&family=Tajawal:wght@200;300;400;500;700;800;900&display=swap');

        * {
            font-family: "Tajawal", sans-serif;
        }

        .wrapper {
            font-family: "Tajawal", sans-serif;
            display: grid;
            grid-template-columns: 2fr .4fr;
            grid-template-rows: 60px;
            gap: 2px;
        }

        h1,
        h2 {
            color: #000;
            text-align: center;
            margin: 10px;
        }

        h3,
        h4 {
            color: #404040;
        }

        i {
            color: #68beb5;
        }

        .header {
            background-color: #F8F9FA;
            grid-column: 1/2;
            grid-row: 1/2;
        }

            .header img {
                width: 60px;
                height: auto;
                float: right;
            }

            .header a i,
            .header span {
                float: left;
                margin-top: 10px;
                padding: 10px;
                color: #8b8b8b;
            }

        .nav {
            background-color: #F8F9FA;
            grid-column: 2/3;
            grid-row: 1/3;
            height: 100vh;
        }

            .nav ul {
                list-style-type: none;
                padding: 10px;
            }

                .nav ul li {
                    padding: 10px 0;
                    float: right;
                }

                    .nav ul li a {
                        text-decoration: none;
                        color: #333;
                        display: flex;
                        align-items: center;
                    }

                    .nav ul li :hover {
                        color: #5aa39b;
                    }

                    .nav ul li a i {
                        padding-left: 10px;
                        color: #68beb5;
                    }

        .main {
            grid-column: 1/2;
            grid-row: 2/3;
            margin: 10px;
            direction: rtl;
        }

            .main button {
                background-color: #5aa39b;
                color: white;
                border-radius: 10px;
                border: none;
                padding-right: 30px;
                padding-left: 30px;
            }

                .main button:hover {
                    background-color: #68beb5;
                }
    </style>

</head>
<body class="wrapper">
    <header class="header">
        <img src="~/Content/logo.PNG" alt="Logo">
        <a href="#"><i class="fas fa-bell"></i></a>
        <a href="#"><i class="fas fa-sign-out-alt"></i></a>
        <span>مرحبا بك </span>
    </header>
    <nav class="nav">
        <h2>نظام التدريب</h2>
        <ul>
            <li>@Html.Raw($"<a href='{Url.Action("Index", "Admin")}' class='body'><span>الصفحة الرئيسية</span> <i class='fas fa-home'></i></a>")</li>
            <li>@Html.Raw($"<a href='{Url.Action("Index", "CourseSchedules")}' class='body'>جدول الدورات<i class='fas fa-calendar-alt'></i></a>")</li>
            <li>@Html.Raw($"<a href='{Url.Action("Create", "CourseSchedules")}' class='body'>إضافة دورة تدريبية<i class='fas fa-plus-circle'></i></a>")</li>
            <li><a href="#"><span>طلبات الدورات</span> <i class="fas fa-file-alt"></i></a></li>
            <li>@Html.Raw($"<a href='{Url.Action("Index", "Registered_in_the_course")}' class='body'>متابعة الحضور<i class='fas fa-check-circle'></i></a>")</li>
            <li><a href="#"><span>إدارة الصلاحيات</span> <i class="fas fa-user-shield"></i></a></li>
            <li><a href="#"><span>قوالب الشهادات</span> <i class="fas fa-certificate"></i></a></li>
            <li><a href="#"><span>إدارة التصنيفات</span> <i class="fas fa-tags"></i></a></li>
            <li>@Html.Raw($"<a href='{Url.Action("ReportsAndStatistics_for_SupportTickets", "Home")}' class='body'>التقارير و الاحصائيات<i class='fas fa-chart-bar'></i></a>")</li>
            <li><a href="#"><span>الدورات الخارجية</span> <i class="fas fa-external-link-alt"></i></a></li>
            <li>@Html.Raw($"<a href='{Url.Action("TicketManagement", "Home")}' class='body'>إدارة تذاكر الدعم<i class='fas fa-ticket-alt'></i></a>")</li>

        </ul>
    </nav>
    <article class="main">
        @RenderBody()
    </article>



    @*@Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/bootstrap")*@
    @RenderSection("scripts", required: false)
</body>
</html>